import CREATE_FLOW_FOLLOW_ON_X_VALIDATORS from './create';
import UPDATE_FLOW_FOLLOW_ON_X_VALIDATORS from './update';

const FOLLOW_ON_X_VALIDATES = {
  create: CREATE_FLOW_FOLLOW_ON_X_VALIDATORS,
  update: UPDATE_FLOW_FOLLOW_ON_X_VALIDATORS,
};

export default FOLLOW_ON_X_VALIDATES;
