FROM golang:1.23-bookworm

ENV GIN_MODE=release

WORKDIR /app
RUN apt-get update && apt-get install -y build-essential git

COPY ./agent-as-a-service/agent-orchestration/backend/go.mod ./
COPY ./agent-as-a-service/agent-orchestration/backend/go.sum ./
RUN go mod download

COPY ./agent-as-a-service/agent-orchestration/backend/ ./
RUN mv ./configs/config.json.local ./configs/config.json

CMD ["go", "run", "server.go"]


