package domain

// Error used for custom error response
type Error struct {
	Code    int
	Message string
}

func (e Error) Error() string {
	return e.Message
}

// ErrorWithMessage ...
func ErrorWithMessage(e *Error, message string) *Error {
	return &Error{
		Code:    e.Code,
		Message: message,
	}
}

var (
	// user api errors

	// ErrInvalidEmail ...
	ErrInvalidEmail = &Error{Code: -1000, Message: "invalid email"}
	// ErrInvalidPassword ...
	ErrInvalidPassword = &Error{Code: -1001, Message: "invalid password"}
	// ErrInvalidUserType ...
	ErrInvalidUserType = &Error{Code: -1002, Message: "invalid user type"}
	// ErrPasswordMismatch ...
	ErrPasswordMismatch = &Error{Code: -1003, Message: "password and confirm password must match"}
	// ErrEmailNotExists ...
	ErrEmailNotExists = &Error{Code: -1004, Message: "email doesn't exist"}
	// ErrEmailAlreadyExists ...
	ErrEmailAlreadyExists = &Error{Code: -1005, Message: "email already exists"}
	// ErrInvalidCredentials ...
	ErrInvalidCredentials = &Error{Code: -1006, Message: "invalid credentials"}
	// ErrInvalidVerificationToken ...
	ErrInvalidVerificationToken = &Error{Code: -1007, Message: "invalid verification token"}
	// ErrInactiveAccount ...
	ErrInactiveAccount = &Error{Code: -1008, Message: "your account is inactive"}
	// ErrMissingPubKey ...
	ErrMissingPubKey = &Error{Code: -1009, Message: "public key is required for lender user"}
	// ErrSendCodeFailed ...
	ErrSendCodeFailed = &Error{Code: -1010, Message: "Send code fail"}
	// ErrPhoneIsInvalid ...
	ErrPhoneIsInvalid = &Error{Code: -1011, Message: "Phone code invalid"}
	// ErrUserInfoPrimetrustIsInvalid ...
	ErrUserInfoPrimetrustIsInvalid = &Error{Code: -1012, Message: "User info is invalid for KYC pre-validate"}
	// ErrUserNotEnoughPrimetrustInfo ...
	ErrUserNotEnoughPrimetrustInfo = &Error{Code: -1013, Message: "User info is not enough to verify KYC"}
	// ErrUserInvalidToken ...
	ErrUserInvalidToken = &Error{Code: -1014, Message: "Token is invalid"}
	// ErrUserNotFound ...
	ErrUserNotFound = &Error{Code: -1015, Message: "User is not found"}
	// ErrUserBannedAlready ...
	ErrUserBannedAlready = &Error{Code: -1016, Message: "User is banned already"}
	// ErrOldPasswordSame ...
	ErrOldPasswordSame = &Error{Code: -1017, Message: "New password should not be same as old password"}
	// ErrPasswordLength ...
	ErrPasswordLength = &Error{Code: -1018, Message: "Your password must be between 8 and 30 characters"}
	// ErrUserBankInforInvalid ...
	ErrUserBankInforInvalid = &Error{Code: -1019, Message: "User bank infor invalid"}
	// ErrUserBankAccountExisted ...
	ErrUserBankAccountExisted = &Error{Code: -1020, Message: "Bank account has existed already!"}
	// ErrUserWalletExisted ...
	ErrUserWalletExisted = &Error{Code: -1021, Message: "User wallet has existed already!"}
	// ErrUserWalletSourceInvalid ...
	ErrUserWalletSourceInvalid = &Error{Code: -1022, Message: "Source is invalid!"}
	// ErrUserWalletGenerateEthereumFailed ...
	ErrUserWalletGenerateEthereumFailed = &Error{Code: -1023, Message: "Cannot generate ethereum wallet."}
	// ErrUserWalletGenerateBitcoinFailed ...
	ErrUserWalletGenerateBitcoinFailed = &Error{Code: -1024, Message: "Cannot generate bitcoin wallet."}
	// ErrUserDocumentInvalidName ...
	ErrUserDocumentInvalidName = &Error{Code: -1025, Message: "Please double check your document name."}
	// ErrUserDocumentCannotChange ...
	ErrUserDocumentCannotChange = &Error{Code: -1026, Message: "You cannot change KYC information. Please contact admin for support."}
	// ErrUserFirstNameInvalid ...
	ErrUserFirstNameInvalid = &Error{Code: -1027, Message: "FirstName is invalid"}
	// ErrUserLastNameInvalid ...
	ErrUserLastNameInvalid = &Error{Code: -1028, Message: "LastName is invalid"}
	// ErrUserDOBInvalid ...
	ErrUserDOBInvalid = &Error{Code: -1029, Message: "DOB is invalid"}
	// ErrUserTaxCountryInvalid ...
	ErrUserTaxCountryInvalid = &Error{Code: -1030, Message: "TaxCountry is invalid"}
	// ErrUserTaxIDNumberInvalid ...
	ErrUserTaxIDNumberInvalid = &Error{Code: -1031, Message: "TaxIDNumber is invalid"}
	// ErrUserAddress1Invalid ...
	ErrUserAddress1Invalid = &Error{Code: -1032, Message: "Address1 is invalid"}
	// ErrUserAddressCityInvalid ...
	ErrUserAddressCityInvalid = &Error{Code: -1033, Message: "AddressCity is invalid"}
	// ErrUserAddressRegionInvalid ...
	ErrUserAddressRegionInvalid = &Error{Code: -1034, Message: "AddressRegion is invalid"}
	// ErrUserAddressPostalCodeInvalid ...
	ErrUserAddressPostalCodeInvalid = &Error{Code: -1035, Message: "AddressPostalCode is invalid"}
	// ErrUserAddressCountryInvalid ...
	ErrUserAddressCountryInvalid = &Error{Code: -1036, Message: "AddressCountry is invalid"}
	// ErrUserPhoneNumberInvalid ...
	ErrUserPhoneNumberInvalid = &Error{Code: -1037, Message: "PhoneNumber is invalid"}
	// ErrUserDocumentInvalid ...
	ErrUserDocumentInvalid = &Error{Code: -1038, Message: "UserDocument is invalid"}
	// ErrUserSocialInvalidType ...
	ErrUserSocialInvalidType = &Error{Code: -1039, Message: "Social type is invalid"}
	// ErrUserNotVerificationEmailLevel ...
	ErrUserNotVerificationEmailLevel = &Error{Code: -1040, Message: "This user need verify email first"}
	// ErrInterestRateInvalid ...
	ErrInterestRateInvalid = &Error{Code: -1041, Message: "Interest rate is invalid"}
	// ErrCollateralThresholdInvalid ...
	ErrCollateralThresholdInvalid = &Error{Code: -1042, Message: "Collateral threshold is invalid"}
	// ErrCollateralReturnInvalid ...
	ErrCollateralReturnInvalid = &Error{Code: -1043, Message: "Collateral return is invalid"}
	// ErrMissingUserDocuments ...
	ErrMissingUserDocuments = &Error{Code: -1044, Message: "User hasn't had any document yet!"}
	// ErrOTPIsInvalid ...
	ErrOTPIsInvalid = &Error{Code: -1045, Message: "OTP not matched or invalidated!"}
	// ErrInvalidHash ...
	ErrInvalidHash = &Error{Code: -1046, Message: "Invalid hash"}
	// ErrExceedOTPTime ...
	ErrExceedOTPTime = &Error{Code: -1047, Message: "Exceed OTP time"}
	// ErrUserBankNotFound ...
	ErrUserBankNotFound = &Error{Code: -1048, Message: "Bank not found"}
	// ErrUserWrongVerifySubmitted ...
	ErrUserWrongVerifySubmitted = &Error{Code: -1049, Message: "Verfification level != submitted"}
	// ErrWrongReserveTransferType ...
	ErrWrongReserveTransferType = &Error{Code: -1050, Message: "Invalid transfer type"}
	// ErrNeedVerifyOTP ...
	ErrNeedVerifyOTP = &Error{Code: -1051, Message: "You need verify OTP first"}
	// ErrOTPWrongParams ...
	ErrOTPWrongParams = &Error{Code: -1052, Message: "Wrong params"}
	// ErrUserDocumentNotFound ...
	ErrUserDocumentNotFound = &Error{Code: -1053, Message: "User document not found"}
	// ErrInvalidDocumentType ...
	ErrInvalidDocumentType = &Error{Code: -1054, Message: "invalid document type"}
	// ErrEmailVerified ...
	ErrEmailVerified = &Error{Code: -1075, Message: "your email is verified"}
	// ErrUserWalletGenerateBEP2Failed ...
	ErrUserWalletGenerateBEP2Failed = &Error{Code: -1076, Message: "Cannot generate bep2 wallet."}
	// ErrUserExistsUserName ...
	ErrUserExistsUserName = &Error{Code: -1077, Message: "Username already exists."}
	// ErrUserExistsReferralCode ...
	ErrUserExistsReferralCode = &Error{Code: -1078, Message: "ReferralCode is existsed"}
	// ErrUserExistsEmailRestricted ...
	ErrUserExistsEmailRestricted = &Error{Code: -1079, Message: "Email is restricted"}

	// reserve api errors

	// ErrReserveTransferToUserNotFound ...
	ErrReserveTransferToUserNotFound = &Error{Code: -2000, Message: "to user is not found"}
	// ErrReserveNotEnoughConstant ...
	ErrReserveNotEnoughConstant = &Error{Code: -2001, Message: "not enough constant"}
	// ErrReserveNotVerifiedKYC ...
	ErrReserveNotVerifiedKYC = &Error{Code: -2002, Message: "not kyc user"}
	// ErrReserveBuyLimitUS ...
	ErrReserveBuyLimitUS = &Error{Code: -2003, Message: "the minimum of buy is 5cst"}
	// ErrReserveBuyLimitNonUS ...
	ErrReserveBuyLimitNonUS = &Error{Code: -2004, Message: "the minimum of buy is 35cst"}
	// ErrReservePrimetrustError ...
	ErrReservePrimetrustError = &Error{Code: -2005, Message: "Primetrust error"}
	// ErrReserveSmartContractError ...
	ErrReserveSmartContractError = &Error{Code: -2006, Message: "SmartContract error"}
	// ErrReserveTransferUserNotFound ...
	ErrReserveTransferUserNotFound = &Error{Code: -2007, Message: "User not found"}
	// ErrReserveTransferSameUser ...
	ErrReserveTransferSameUser = &Error{Code: -2008, Message: "Cannot transfer to your self"}
	// ErrReserveImportConstantTooFast ...
	ErrReserveImportConstantTooFast = &Error{Code: -2009, Message: "Import the same Constant amount in 2 minutes!"}
	// ErrReserveNotFound ...
	ErrReserveNotFound = &Error{Code: -2010, Message: "Reserve not found!"}
	// ErrReserveNotSupport ...
	ErrReserveNotSupport = &Error{Code: -2011, Message: "Not support this reserve type now!"}
	// ErrReserveInvalidStatus ...
	ErrReserveInvalidStatus = &Error{Code: -2012, Message: "Cannot retry redeem wrong reserve status!"}

	// general api errors

	// ErrInvalidArgument ...
	ErrInvalidArgument = &Error{Code: -9000, Message: "invalid argument"}
	// ErrInternalServerError ...
	ErrInternalServerError = &Error{Code: -9001, Message: "internal server error"}
	// ErrInvalidLimit ...
	ErrInvalidLimit = &Error{Code: -9002, Message: "invalid limit"}
	// ErrInvalidPage ...
	ErrInvalidPage = &Error{Code: -9003, Message: "invalid page"}
	// ErrSystemError ...
	ErrSystemError = &Error{Code: -9004, Message: "system error"}
	// ErrPermissionDenied ...
	ErrPermissionDenied = &Error{Code: -9005, Message: "permission denied"}
	// ErrUnauthorized ...
	ErrUnauthorized = &Error{Code: -9006, Message: "Unauthorized"}
	// ErrNotFound will throw if the requested item is not exists
	ErrNotFound = &Error{Code: -9007, Message: "Your requested Item is not found"}
	// ErrConflict will throw if the current action already exists
	ErrConflict = &Error{Code: -9008, Message: "Your Item already exist"}
	// ErrBadParamInput ...
	ErrBadParamInput = &Error{Code: -9009, Message: "Given Param is not valid"}
	// ErrCheckUserBalance ...
	ErrCheckUserBalance = &Error{Code: -9010, Message: "User check balance error"}

	// storage api errors

	// ErrFileInvalidRequest ...
	ErrFileInvalidRequest = &Error{Code: -8000, Message: "invalid request"}
	// ErrFileInvalid ...
	ErrFileInvalid = &Error{Code: -8001, Message: "file invalid"}
	// ErrSizeLimit ...
	ErrSizeLimit = &Error{Code: -8002, Message: "invalid file size"}
	// ErrFileType ...
	ErrFileType = &Error{Code: -8003, Message: "invalid file type"}
	// ErrSubmitFileFail ...
	ErrSubmitFileFail = &Error{Code: -8004, Message: "submit file failed"}

	// local api errors

	// ErrLocalNotEnoughConstantBalance ...
	ErrLocalNotEnoughConstantBalance = &Error{Code: -3000, Message: "Your Constant balance is not enough to create this order"}
	// ErrLocalCannotCancelOrderID ...
	ErrLocalCannotCancelOrderID = &Error{Code: -3001, Message: "Cannot cancel this order id"}
	// ErrLocalInvalidInitOrder ...
	ErrLocalInvalidInitOrder = &Error{Code: -3002, Message: "Type should be Sell/Buy"}
	// ErrLocalExchangeRateNotFound ...
	ErrLocalExchangeRateNotFound = &Error{Code: -3003, Message: "Cannot find exchange rate"}
	// ErrLocalConstantAmount ...
	ErrLocalConstantAmount = &Error{Code: -3004, Message: "Your Constant must be less or equal 2000"}
	// ErrLocalPriceAmount ...
	ErrLocalPriceAmount = &Error{Code: -3005, Message: "Your price must be large than 0"}
	// ErrLocalInvalidPrice ...
	ErrLocalInvalidPrice = &Error{Code: -3006, Message: "Your price doesn't match with your list"}
	// ErrLocalApproveOrderWrongStatus ...
	ErrLocalApproveOrderWrongStatus = &Error{Code: -3007, Message: "Please double check status of your order"}
	// ErrLocalWrongType ...
	ErrLocalWrongType = &Error{Code: -3008, Message: "Please double check order type"}
	// ErrLocalWrongID ...
	ErrLocalWrongID = &Error{Code: -3009, Message: "You are not owner of this order id"}
	// ErrLocalMatchMySelf ...
	ErrLocalMatchMySelf = &Error{Code: -3010, Message: "You cannot Buy/Sell with yourself"}
	// ErrLocalInvalidConstant ...
	ErrLocalInvalidConstant = &Error{Code: -3011, Message: "Please check your Constant"}
	// ErrLocalInvalidBankAccountName ...
	ErrLocalInvalidBankAccountName = &Error{Code: -3012, Message: "Please check your bank account name"}
	// ErrLocalInvalidBankAccountNumber ...
	ErrLocalInvalidBankAccountNumber = &Error{Code: -3013, Message: "Please check your bank account number"}
	// ErrLocalInvalidRoutingAndSwiftCode ...
	ErrLocalInvalidRoutingAndSwiftCode = &Error{Code: -3014, Message: "Please check your routing number or swift code"}
	// ErroLocalInvalidBankName ...
	ErroLocalInvalidBankName = &Error{Code: -3015, Message: "Please check your bank name"}
	// ErroLocalCannotApproveOrder ...
	ErroLocalCannotApproveOrder = &Error{Code: -3016, Message: "You cannot approve this order. Please contact hello@constant.money for support"}
	// ErroLocalCannotFinishOrder ...
	ErroLocalCannotFinishOrder = &Error{Code: -3017, Message: "You cannot finish this order. Please contact hello@constant.money for support"}
	// ErrLocalTransactionError ...
	ErrLocalTransactionError = &Error{Code: -3018, Message: "Transation Error"}
	// ErrLocalMissingBankInfo ...
	ErrLocalMissingBankInfo = &Error{Code: -3019, Message: "There is no bank info of user"}
	// ErrLocalMissingBankAnotherInfo ...
	ErrLocalMissingBankAnotherInfo = &Error{Code: -3020, Message: "There is no bank branch"}
	// ErrLocalMissingBankCountry ...
	ErrLocalMissingBankCountry = &Error{Code: -3021, Message: "There is no bank country"}

	// loan api errors

	// ErrLoanInvalidNextPay ...
	ErrLoanInvalidNextPay = &Error{Code: -9000, Message: "Next payment invalid"}
	// ErrInterestRateNotFound ...
	ErrInterestRateNotFound = &Error{Code: -9001, Message: "Interest rate not found"}
	// ErrCollateralNotFound ...
	ErrCollateralNotFound = &Error{Code: -9002, Message: "Collateral not found"}
	// GenerateEthereumFail ...
	GenerateEthereumFail = &Error{Code: -9003, Message: "Generate Ethereum wallet failed"}
	// GenerateBitcoinFail ...
	GenerateBitcoinFail = &Error{Code: -9004, Message: "Generate Bitcoin wallet failed"}
	// GenerateCollateralAmountFail ...
	GenerateCollateralAmountFail = &Error{Code: -9005, Message: "Generate Collateral Amount failed"}
	// CreateCollateralFail ...
	CreateCollateralFail = &Error{Code: -9006, Message: "Create Collateral failed"}
	// UpdateCollateralFail ...
	UpdateCollateralFail = &Error{Code: -9007, Message: "Update Collateral failed"}
	// CollateralExchangeRateFail ...
	CollateralExchangeRateFail = &Error{Code: -9008, Message: "Get exchange rate failed"}
	// ReceiveAddressInvalid ...
	ReceiveAddressInvalid = &Error{Code: -9009, Message: "Receive address invalid"}
	// ErrCollateralPeriodInvalid ...
	ErrCollateralPeriodInvalid = &Error{Code: -9010, Message: "Period invalid"}
	// ErrCollateralInterestRateInvalid ...
	ErrCollateralInterestRateInvalid = &Error{Code: -9011, Message: "Interest Rate invalid"}
	// ErrCollateralWrongStatus ...
	ErrCollateralWrongStatus = &Error{Code: -9012, Message: "Please double check status of your loan"}
	// ErrCollateralStatusNotFound ...
	ErrCollateralStatusNotFound = &Error{Code: -9013, Message: "Collateral status not found"}
	// ErrBalanceHoldingInvalid ...
	ErrBalanceHoldingInvalid = &Error{Code: -9014, Message: "Collateral loan balance holding invalid"}
	// ErrCollateralLoanSymbolNotfound ...
	ErrCollateralLoanSymbolNotfound = &Error{Code: -9014, Message: "Collateral loan symbol not found"}
	// ErrCollateralLoanSymbolResponseNotfound ...
	ErrCollateralLoanSymbolResponseNotfound = &Error{Code: -9015, Message: "Collateral loan symbol response not found"}
	// ErrCollateralLoanSymbolReateResponseNotfound ...
	ErrCollateralLoanSymbolReateResponseNotfound = &Error{Code: -9016, Message: "Collateral loan symbol rate response not found"}
	// ErrCollateralLoanAcceptFail ...
	ErrCollateralLoanAcceptFail = &Error{Code: -9015, Message: "Collateral loan accept failed"}
	// ErrCollateralLoanNotPermission ...
	ErrCollateralLoanNotPermission = &Error{Code: -9016, Message: "Collateral loan is not permission"}
	// ErrCollateralLoanCancelFailed ...
	ErrCollateralLoanCancelFailed = &Error{Code: -9017, Message: "Collateral loan cancel failed"}
	// ErrCollateralBalanceFailed ...
	ErrCollateralBalanceFailed = &Error{Code: -9018, Message: "Collateral user balance failed"}
	// ErrCollateralBTCNotFound ...
	ErrCollateralBTCNotFound = &Error{Code: -9019, Message: "Collateral BTC not found"}
	// ErrCollateralETHNotFound ...
	ErrCollateralETHNotFound = &Error{Code: -9020, Message: "Collateral not ETH found"}
	// ErrCollateralERC20NotFound ...
	ErrCollateralERC20NotFound = &Error{Code: -9021, Message: "Collateral not ERC20 found"}
	// ErrCollateralTOMONotFound ...
	ErrCollateralTOMONotFound = &Error{Code: -9022, Message: "Collateral not ERC20 found"}

	// loan pro api errors

	// ErrCollateralLoanMatchedPayNotFound ...
	ErrCollateralLoanMatchedPayNotFound = &Error{Code: -10001, Message: "Collateral loan matched pay not found"}
	// ErrCollateralLoanMatchedPayNotEnoughConstantBalance ...
	ErrCollateralLoanMatchedPayNotEnoughConstantBalance = &Error{Code: -10002, Message: "Your Constant balance is not enough to pay this matched"}
	// ErrLoanMasterAccountNotEnoughConstantBalance ...
	ErrLoanMasterAccountNotEnoughConstantBalance = &Error{Code: -10003, Message: "Loan master account's Constant balance is not enough to pay this matched"}
	// ErrUserCollateralNotFound ...
	ErrUserCollateralNotFound = &Error{Code: -10004, Message: "User collaterral loan not found"}
	// ErrGetCollateralCurrentRateInvalid ...
	ErrGetCollateralCurrentRateInvalid = &Error{Code: -10005, Message: "Get collaterral rate invalid"}
	// ErrGetCollateralGetExchangeRateFail ...
	ErrGetCollateralGetExchangeRateFail = &Error{Code: -10006, Message: "Get collaterral get exchange rate failed"}
	// ErrCollateralLoanMatchedStatusInvalid ...
	ErrCollateralLoanMatchedStatusInvalid = &Error{Code: -10007, Message: "Collaterral loan matched status invalid"}
	// ErrCollateralLoanMatchedContractInvalid ...
	ErrCollateralLoanMatchedContractInvalid = &Error{Code: -10008, Message: "Collaterral loan matched contract invalid"}
	// ErrCollateralLoanMatchedExisted ...
	ErrCollateralLoanMatchedExisted = &Error{Code: -10009, Message: "Collaterral loan matched existed"}
	// ErrCollateralLoanMatchedPayUserInvalid ...
	ErrCollateralLoanMatchedPayUserInvalid = &Error{Code: -10010, Message: "Collateral loan matched pay user invalid"}

	//11xxx
	ErrUserCouponUsed                      = &Error{Code: -11001, Message: "Coupon has already used"}
	ErrUserCouponInvalid                   = &Error{Code: -11002, Message: "Coupon is invalid"}
	ErrUserTransferingAccountInvalid       = &Error{Code: -11003, Message: "Transfering account is invalid"}
	ErrUserTransferingAccountBalanceFailed = &Error{Code: -11004, Message: "Not enough balance"}
)
