import CREATE_FLOW_POST_ON_FARCASTER_VALIDATORS from './create';
import UPDATE_FLOW_POST_ON_FARCASTER_VALIDATORS from './update';

const POST_ON_FARCASTER_VALIDATES = {
  create: CREATE_FLOW_POST_ON_FARCASTER_VALIDATORS,
  update: UPDATE_FLOW_POST_ON_FARCASTER_VALIDATORS,
};

export default POST_ON_FARCASTER_VALIDATES;
