import CREATE_FLOW_ENGAGE_ON_X_VALIDATORS from './create';
import UPDATE_FLOW_ENGAGE_ON_X_VALIDATORS from './update';

const ENGAGE_ON_X_VALIDATES = {
  create: CREATE_FLOW_ENGAGE_ON_X_VALIDATORS,
  update: UPDATE_FLOW_ENGAGE_ON_X_VALIDATORS,
};

export default ENGAGE_ON_X_VALIDATES;
