export enum EMissionToolSet {
  DEFAULT = "default",
  REPLY_MENTIONS = "reply_mentions",
  REPLY_NON_MENTIONS = "reply_non_mentions",
  FOLLOW = "follow",
  POST = "post",
  POST_SEARCH = "post_search",
  ENGAGE = "engage",
  CREATE_TOKEN = "create_token",
  TRADING = "trading",
  POST_FARCASTER = "post_farcaster",
  REPLY_MENTIONS_FARCASTER = "reply_mentions_farcaster",
  TRADING_FARCASTER = "trading_farcaster",
  POST_SEARCH_FARCASTER = "post_search_farcaster",
  POST_SEARCH_V2 = "post_search_v2",
  POST_SEARCH_V3 = "post_search_v3",
  LUCKY_MONEY = "lucky_moneys",
  DEFI_TRADE_ANALYTICS = "trade_analytics_twitter",
}
