import CREATE_FLOW_NEW_AGENT_VALIDATORS from "./create";
import UPDATE_FLOW_NEW_AGENT_VALIDATORS from "./update";

const NEW_AGENT_VALIDATES = {
  create: CREATE_FLOW_NEW_AGENT_VALIDATORS,
  update: UPDATE_FLOW_NEW_AGENT_VALIDATORS,
};

export default NEW_AGENT_VALIDATES;
