import { CREATE_DECENTRALIZE_INFERENCE } from './create';
import { UPDATE_DECENTRALIZE_INFERENCE } from './update';

export const DECENTRALIZE_INFERENCE_VALIDATES = {
  create: CREATE_DECENTRALIZE_INFERENCE,
  update: UPDATE_DECENTRALIZE_INFERENCE,
};
