from x_content.constants.utils import get_and_warn

TELEGRAM_API_KEY = get_and_warn("TELEGRAM_API_KEY")

TELEGRAM_ROOM = get_and_warn("TELEGRAM_ROOM")
TELEGRAM_BOTNAME = get_and_warn("TELEGRAM_BOTNAME")
TELEGRAM_ALERT_ROOM = get_and_warn("TELEGRAM_ALERT_ROOM")
DISABLED_TELEGRAM_USERS = get_and_warn("DISABLED_TELEGRAM_USERS", "")
TELEGRAM_IO_NOTIFICATIONS_ROOM = get_and_warn(
    "TELEGRAM_IO_NOTIFICATIONS_ROOM"
)
TELEGRAM_TASK_IO_NOTIFICATION_ROOM = get_and_warn(
    "TELEGRAM_TASK_IO_NOTIFICATION_ROOM"
)
TELEGRAM_MESSAGE_LENGTH_LIMIT = 4096  # characters
TELEGRAM_MESSAGE_LIST_REDIS_KEY = "telegram_message_list"

DISABLE_JUNK_NOTIFICATIONS = (
    get_and_warn("DISABLE_JUNK_NOTIFICATIONS") or False
)

if isinstance(DISABLE_JUNK_NOTIFICATIONS, str):
    DISABLE_JUNK_NOTIFICATIONS = DISABLE_JUNK_NOTIFICATIONS.lower() in [
        "true",
        "1",
    ]
