package configs

var BINANCE_TOKENS = []string{
	"BTC",
	"ETH",
	"BNB",
	"NEO",
	"LTC",
	"ADA",
	"XRP",
	"EOS",
	"IOTA",
	"XLM",
	"TRX",
	"ETC",
	"ICX",
	"NULS",
	"VET",
	"LINK",
	"ONG",
	"HOT",
	"ZIL",
	"ZRX",
	"FET",
	"BAT",
	"ZEC",
	"IOST",
	"CELR",
	"DASH",
	"THETA",
	"ENJ",
	"ATOM",
	"TFUEL",
	"ONE",
	"ALGO",
	"DOGE",
	"DUSK",
	"ANKR",
	"WIN",
	"COS",
	"MTL",
	"DENT",
	"WAN",
	"FUN",
	"CHZ",
	"BAND",
	"XTZ",
	"RVN",
	"HBAR",
	"NKN",
	"STX",
	"KAVA",
	"ARPA",
	"IOTX",
	"RLC",
	"CTXC",
	"BCH",
	"TROY",
	"VITE",
	"EUR",
	"OGN",
	"LSK",
	"BNT",
	"LTO",
	"MBL",
	"COTI",
	"STPT",
	"DATA",
	"SOL",
	"CTSI",
	"HIVE",
	"CHR",
	"ARDR",
	"MDT",
	"STMX",
	"KNC",
	"LRC",
	"COMP",
	"SC",
	"ZEN",
	"SNX",
	"VTHO",
	"DGB",
	"SXP",
	"MKR",
	"DCR",
	"STORJ",
	"MANA",
	"YFI",
	"BAL",
	"KMD",
	"JST",
	"CRV",
	"SAND",
	"NMR",
	"DOT",
	"LUNA",
	"RSR",
	"PAXG",
	"TRB",
	"SUSHI",
	"KSM",
	"EGLD",
	"DIA",
	"RUNE",
	"FIO",
	"UMA",
	"BEL",
	"WING",
	"UNI",
	"OXT",
	"SUN",
	"AVAX",
	"FLM",
	"UTK",
	"XVS",
	"ALPHA",
	"AAVE",
	"NEAR",
	"FIL",
	"INJ",
	"AUDIO",
	"CTK",
	"AXS",
	"HARD",
	"ROSE",
	"AVA",
	"SKL",
	"GRT",
	"JUV",
	"PSG",
	"1INCH",
	"OG",
	"ATM",
	"ASR",
	"CELO",
	"RIF",
	"TRU",
	"CKB",
	"TWT",
	"FIRO",
	"LIT",
	"SFP",
	"DODO",
	"CAKE",
	"ACM",
	"BADGER",
	"FIS",
	"OM",
	"POND",
	"DEGO",
	"ALICE",
	"LINA",
	"PERP",
	"SUPER",
	"CFX",
	"TKO",
	"PUNDIX",
	"TLM",
	"BAR",
	"FORTH",
	"BAKE",
	"BURGER",
	"SLP",
	"SHIB",
	"ICP",
	"AR",
	"MASK",
	"LPT",
	"XVG",
	"ATA",
	"GTC",
	"ERN",
	"PHA",
	"MLN",
	"DEXE",
	"C98",
	"CLV",
	"QNT",
	"FLOW",
	"MINA",
	"RAY",
	"FARM",
	"ALPACA",
	"MBOX",
	"REQ",
	"GHST",
	"WAXP",
	"GNO",
	"XEC",
	"ELF",
	"DYDX",
	"IDEX",
	"GALA",
	"ILV",
	"YGG",
	"SYS",
	"DF",
	"FIDA",
	"AGLD",
	"RAD",
	"BETA",
	"RARE",
	"LAZIO",
	"CHESS",
	"ADX",
	"AUCTION",
	"MOVR",
	"CITY",
	"ENS",
	"QI",
	"PORTO",
	"POWR",
	"JASMY",
	"AMP",
	"PYR",
	"ALCX",
	"SANTOS",
	"BICO",
	"FLUX",
	"FXS",
	"VOXEL",
	"HIGH",
	"CVX",
	"PEOPLE",
	"SPELL",
	"JOE",
	"ACH",
	"IMX",
	"GLMR",
	"LOKA",
	"SCRT",
	"API3",
	"BTTC",
	"ACA",
	"XNO",
	"WOO",
	"ALPINE",
	"T",
	"ASTR",
	"GMT",
	"KDA",
	"APE",
	"BSW",
	"BIFI",
	"STEEM",
	"NEXO",
	"REI",
	"LDO",
	"OP",
	"LEVER",
	"STG",
	"LUNC",
	"GMX",
	"POLYX",
	"APT",
	"OSMO",
	"HFT",
	"VIDT",
	"PHB",
	"HOOK",
	"MAGIC",
	"HIFI",
	"RPL",
	"PROS",
	"GNS",
	"BNX",
	"SYN",
	"VIB",
	"SSV",
	"LQTY",
	"AMB",
	"USTC",
	"TUSD",
	"USDC",
	"USDP",
	"GAS",
	"GLM",
	"PROM",
	"QKC",
	"UFT",
	"ID",
	"ARB",
	"RDNT",
	"WBTC",
	"EDU",
	"SUI",
	"AERGO",
	"PEPE",
	"FLOKI",
	"CVC",
	"AST",
	"SNT",
	"COMBO",
	"MAV",
	"PENDLE",
	"ARKM",
	"WBETH",
	"QUICK",
	"WLD",
	"FDUSD",
	"SEI",
	"CYBER",
	"FTT",
	"ARK",
	"CREAM",
	"IQ",
	"NTRN",
	"TIA",
	"MEME",
	"ORDI",
	"BEAMX",
	"PIVX",
	"VIC",
	"BLUR",
	"VANRY",
	"JTO",
	"AEUR",
	"1000SATS",
	"BONK",
	"ACE",
	"NFP",
	"AI",
	"XAI",
	"MANTA",
	"ALT",
	"JUP",
	"PYTH",
	"RONIN",
	"DYM",
	"PIXEL",
	"STRK",
	"PORTAL",
	"PDA",
	"AXL",
	"WIF",
	"METIS",
	"AEVO",
	"BOME",
	"ETHFI",
	"STRAX",
	"ENA",
	"W",
	"TNSR",
	"SAGA",
	"TAO",
	"OMNI",
	"REZ",
	"BB",
	"NOT",
	"IO",
	"ZK",
	"LISTA",
	"ZRO",
	"G",
	"BANANA",
	"RENDER",
	"TON",
	"DOGS",
	"EURI",
	"SLF",
	"POL",
	"NEIRO",
	"TURBO",
	"1MBABYDOGE",
	"CATI",
	"HMSTR",
	"EIGEN",
	"BNSOL",
	"LUMIA",
	"SCR",
	"KAIA",
	"COW",
	"CETUS",
	"PNUT",
	"ACT",
	"THE",
	"ACX",
	"ORCA",
	"MOVE",
	"ME",
	"VELODROME",
	"VANA",
	"1000CAT",
	"USUAL",
	"PENGU",
	"BIO",
	"D",
	"AIXBT",
	"CGPT",
	"COOKIE",
	"QTUM",
	"ONT",
}

var MISSION_TOKEN_CONFIGS = []map[string]string{
	{
		"symbol":    "BTC",
		"name":      "Bitcoin",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
	},
	{
		"symbol":    "ETH",
		"name":      "Ethereum",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
	},
	{
		"symbol":    "USDT",
		"name":      "Tether USDt",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/825.png",
	},
	{
		"symbol":    "XRP",
		"name":      "XRP",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/52.png",
	},
	{
		"symbol":    "BNB",
		"name":      "Binance Coin",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
	},
	{
		"symbol":    "SOL",
		"name":      "Solana",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png",
	},
	{
		"symbol":    "DOGE",
		"name":      "Dogecoin",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/74.png",
	},
	{
		"symbol":    "USDC",
		"name":      "USDC",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png",
	},
	{
		"symbol":    "ADA",
		"name":      "Cardano",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/2010.png",
	},
	{
		"symbol":    "TRX",
		"name":      "TRON",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1958.png",
	},
	{
		"symbol":    "AVAX",
		"name":      "Avalanche",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png",
	},
	{
		"symbol":    "LINK",
		"name":      "Chainlink",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1975.png",
	},
	{
		"symbol":    "TON",
		"name":      "Toncoin",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/11419.png",
	},
	{
		"symbol":    "SHIB",
		"name":      "Shiba Inu",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/5994.png",
	},
	{
		"symbol":    "SUI",
		"name":      "Sui Crypto",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/20947.png",
	},
	{
		"symbol":    "HBAR",
		"name":      "Hedera Hashgraph",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/4642.png",
	},
	{
		"symbol":    "XLM",
		"name":      "Stellar",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/512.png",
	},
	{
		"symbol":    "DOT",
		"name":      "Polkadot",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/6636.png",
	},
	{
		"symbol":    "BCH",
		"name":      "Bitcoin Cash",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1831.png",
	},
	{
		"symbol":    "BGB",
		"name":      "Bitget Token",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/11092.png",
	},
	{
		"symbol":    "LEO",
		"name":      "UNUS SED LEO",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/3957.png",
	},
	{
		"symbol":    "LTC",
		"name":      "Litecoin",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/2.png",
	},
	{
		"symbol":    "UNI",
		"name":      "Uniswap",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/7083.png",
	},
	{
		"symbol":    "PEPE",
		"name":      "Pepe Coin",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/24478.png",
	},
	{
		"symbol":    "NEAR",
		"name":      "NEAR Protocol",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/6535.png",
	},
	{
		"symbol":    "DAI",
		"name":      "Dai",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/4943.png",
	},
	{
		"symbol":    "AAVE",
		"name":      "Aave",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/7278.png",
	},
	{
		"symbol":    "APT",
		"name":      "Aptos",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/21794.png",
	},
	{
		"symbol":    "ICP",
		"name":      "Internet Computer",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/8916.png",
	},
	{
		"symbol":    "POL",
		"name":      "POL (ex-MATIC)",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/28321.png",
	},
	{
		"symbol":    "CRO",
		"name":      "Cronos",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/3635.png",
	},
	{
		"symbol":    "MNT",
		"name":      "Mantle",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/27075.png",
	},
	{
		"symbol":    "ETC",
		"name":      "Ethereum Classic",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1321.png",
	},
	{
		"symbol":    "VET",
		"name":      "VeChain",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/3077.png",
	},
	{
		"symbol":    "RENDER",
		"name":      "Render",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/5690.png",
	},
	{
		"symbol":    "XMR",
		"name":      "Monero",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/328.png",
	},
	{
		"symbol":    "TAO",
		"name":      "Bittensor",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/22974.png",
	},
	{
		"symbol":    "OM",
		"name":      "MANTRA DAO",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/6536.png",
	},
	{
		"symbol":    "ARB",
		"name":      "Arbitrum",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/11841.png",
	},
	{
		"symbol":    "FET",
		"name":      "Fetch.ai",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/3773.png",
	},
	{
		"symbol":    "FIL",
		"name":      "Filecoin",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/2280.png",
	},
	{
		"symbol":    "OKB",
		"name":      "OKB",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/3897.png",
	},
	{
		"symbol":    "ALGO",
		"name":      "Algorand",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/4030.png",
	},
	{
		"symbol":    "KAS",
		"name":      "Kaspa",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/20396.png",
	},
	{
		"symbol":    "ENA",
		"name":      "Ethena",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/30171.png",
	},
	{
		"symbol":    "FTM",
		"name":      "Fantom",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/3513.png",
	},
	{
		"symbol":    "ATOM",
		"name":      "Cosmos",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/3794.png",
	},
	{
		"symbol":    "BONK",
		"name":      "Bonk",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/23095.png",
	},
	{
		"symbol":    "OP",
		"name":      "Optimism",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/11840.png",
	},
	{
		"symbol":    "STX",
		"name":      "Stacks",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/4847.png",
	},
	{
		"symbol":    "IMX",
		"name":      "Immutable X",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/10603.png",
	},
	{
		"symbol":    "TIA",
		"name":      "Celestia",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/22861.png",
	},
	{
		"symbol":    "THETA",
		"name":      "Theta Token",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/2416.png",
	},
	{
		"symbol":    "INJ",
		"name":      "Injective",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/7226.png",
	},
	{
		"symbol":    "FDUSD",
		"name":      "First Digital USD",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/26081.png",
	},
	{
		"symbol":    "ONDO",
		"name":      "Ondo Finance",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/21159.png",
	},
	{
		"symbol":    "GRT",
		"name":      "The Graph",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/6719.png",
	},
	{
		"symbol":    "WIF",
		"name":      "Dogwifhat",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/28752.png",
	},
	{
		"symbol":    "JASMY",
		"name":      "Jasmy",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/8425.png",
	},
	{
		"symbol":    "SEI",
		"name":      "Sei",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/23149.png",
	},
	{
		"symbol":    "WLD",
		"name":      "Worldcoin",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/13502.png",
	},
	{
		"symbol":    "RUNE",
		"name":      "THORChain",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/4157.png",
	},
	{
		"symbol":    "FLOKI",
		"name":      "Floki Inu",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/10804.png",
	},
	{
		"symbol":    "LDO",
		"name":      "Lido DAO Token",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/8000.png",
	},
	{
		"symbol":    "FLR",
		"name":      "Flare",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/7950.png",
	},
	{
		"symbol":    "RAY",
		"name":      "Raydium",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/8526.png",
	},
	{
		"symbol":    "XTZ",
		"name":      "Tezos",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/2011.png",
	},
	{
		"symbol":    "MKR",
		"name":      "Maker",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1518.png",
	},
	{
		"symbol":    "QNT",
		"name":      "Quant",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/3155.png",
	},
	{
		"symbol":    "SAND",
		"name":      "The Sandbox",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/6210.png",
	},
	{
		"symbol":    "GT",
		"name":      "GateToken",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/4269.png",
	},
	{
		"symbol":    "BEAM",
		"name":      "Beam",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/28298.png",
	},
	{
		"symbol":    "PYTH",
		"name":      "Pyth Network",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/28177.png",
	},
	{
		"symbol":    "GALA",
		"name":      "GALA",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/7080.png",
	},
	{
		"symbol":    "KCS",
		"name":      "KuCoin Token",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/2087.png",
	},
	{
		"symbol":    "BRETT",
		"name":      "Brett (Based)",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/29743.png",
	},
	{
		"symbol":    "EOS",
		"name":      "EOS",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1765.png",
	},
	{
		"symbol":    "CRV",
		"name":      "Curve DAO Token",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/6538.png",
	},
	{
		"symbol":    "HNT",
		"name":      "Helium",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/5665.png",
	},
	{
		"symbol":    "XDC",
		"name":      "XDC Network",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/2634.png",
	},
	{
		"symbol":    "ENS",
		"name":      "Ethereum Name Service",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/13855.png",
	},
	{
		"symbol":    "JUP",
		"name":      "Jupiter",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/29210.png",
	},
	{
		"symbol":    "FTT",
		"name":      "FTX Token",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/4195.png",
	},
	{
		"symbol":    "ZEC",
		"name":      "Zcash",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1437.png",
	},
	{
		"symbol":    "FLOW",
		"name":      "Flow",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/4558.png",
	},
	{
		"symbol":    "AR",
		"name":      "Arweave",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/5632.png",
	},
	{
		"symbol":    "DYDX",
		"name":      "dYdX (Native)",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/28324.png",
	},
	{
		"symbol":    "IOTA",
		"name":      "IOTA",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1720.png",
	},
	{
		"symbol":    "BSV",
		"name":      "Bitcoin SV",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/3602.png",
	},
	{
		"symbol":    "BTT",
		"name":      "BitTorrent",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/16086.png",
	},
	{
		"symbol":    "STRK",
		"name":      "Starknet",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/22691.png",
	},
	{
		"symbol":    "CORE",
		"name":      "Core",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/23254.png",
	},
	{
		"symbol":    "AXS",
		"name":      "Axie Infinity",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/6783.png",
	},
	{
		"symbol":    "AIOZ",
		"name":      "AIOZ Network",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/9104.png",
	},
	{
		"symbol":    "NEO",
		"name":      "NEO",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1376.png",
	},
	{
		"symbol":    "MANA",
		"name":      "Decentraland",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/1966.png",
	},
	{
		"symbol":    "MOG",
		"name":      "Mog Coin",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/27659.png",
	},
	{
		"symbol":    "EGLD",
		"name":      "MultiversX (Elrond)",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/6892.png",
	},
	{
		"symbol":    "MATIC",
		"name":      "Polygon",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png",
	},
	{
		"symbol":    "APE",
		"name":      "ApeCoin",
		"image_url": "https://s2.coinmarketcap.com/static/img/coins/64x64/18876.png",
	},
}
