import CREATE_FLOW_TRADE_ANALYTICS_ON_DEFI_VALIDATORS from './create';
import UPDATE_FLOW_TRADE_ANALYTICS_ON_DEFI_VALIDATORS from './update';

const TRADE_ANALYTICS_ON_DEFI_VALIDATES = {
  create: CREATE_FLOW_TRADE_ANALYTICS_ON_DEFI_VALIDATORS,
  update: UPDATE_FLOW_TRADE_ANALYTICS_ON_DEFI_VALIDATORS,
};

export default TRADE_ANALYTICS_ON_DEFI_VALIDATES;
