import CREATE_FLOW_TRADING_ON_X_VALIDATORS from './create';
import UPDATE_FLOW_TRADING_ON_X_VALIDATORS from './update';

const TRADING_ON_X_VALIDATES = {
  create: CREATE_FLOW_TRADING_ON_X_VALIDATORS,
  update: UPDATE_FLOW_TRADING_ON_X_VALIDATORS,
};

export default TRADING_ON_X_VALIDATES;
