FROM golang:1.23-bookworm

ENV GIN_MODE=release

WORKDIR /app
RUN apt-get update && apt-get install -y build-essential git

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY ./ ./
RUN mv ./configs/config.json.local ./configs/config.json

CMD ["go", "run", "server.go"]


