import CREATE_FARCASTER_VALIDATORS from "./create";
import UPDATE_FARCASTER_VALIDATORS from "./update";

const FARCASTER_VALIDATES = {
  create: CREATE_FARCASTER_VALIDATORS,
  update: UPDATE_FARCASTER_VALIDATORS,
};

export default FARCASTER_VALIDATES;
