import CREATE_FLOW_POST_FOLLOWING_ON_X_VALIDATORS from './create';
import UPDATE_FLOW_POST_FOLLOWING_ON_X_VALIDATORS from './update';

const POST_FOLLOWING_ON_X_VALIDATES = {
  create: CREATE_FLOW_POST_FOLLOWING_ON_X_VALIDATORS,
  update: UPDATE_FLOW_POST_FOLLOWING_ON_X_VALIDATORS,
};

export default POST_FOLLOWING_ON_X_VALIDATES;
